[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hello_package"
version = "0.1.0"
description = "A package to perform complex analysis"
authors = [
{ name="Example Author", email="author@example.com" },
]
dependencies = ["numpy<2.0",
    "matplotlib>=3.4",
]

[tool.setuptools.packages.find]
include = ["hello_package*"]
exclude = ["n"]